name: Release

on:
  push:
    branches:
      - master
    paths-ignore:
      - 'README.md'
      - '.gitignore'
      - 'LICENSE'

jobs:
  windows-release-build:
    name: Windows Latest Build
    permissions:
      contents: write
    runs-on: windows-latest
    outputs:
      new_tag: ${{ steps.tag_version.outputs.new_tag }}
      changelog: ${{ steps.tag_version.outputs.changelog }}
    steps:
      - name: Check-out repository
        uses: actions/checkout@v4

      - name: Setup .Net Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0'

      - name: Bump version and push tag
        id: tag_version
        uses: mathieudutour/github-tag-action@v6.2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          pre_release_branches: "fast"

      - name: Clone `Change-Log-File-Generator` Python script
        run: git clone https://github.com/T2PeNBiX99wcoxKv3A4g/Change-Log-File-Generator.git .change-log-generator

      - name: Clone `CSharp-Workflow-Scripts` Python script
        run: git clone https://github.com/T2PeNBiX99wcoxKv3A4g/CSharp-Workflow-Scripts.git .scripts

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '>=3.13.7'
          cache: 'pip'

      - name: Install Dependencies
        run: |
          pip install -r .change-log-generator/requirements.txt
          pip install -r .scripts/requirements.txt

      - name: Create `CHANGELOG.md` file
        run: |
          $changeLog = @"
          ${{ steps.tag_version.outputs.changelog }}
          "@
          python .change-log-generator/change_log_generator.py $changeLog

      - name: Change version in `Main.cs`
        run: python .scripts/change_version.py ./Main.cs Version ${{ steps.tag_version.outputs.new_tag }}

      - name: Remove all python scripts
        run: |
          Remove-Item -Force -Recurse .scripts
          Remove-Item -Force -Recurse .change-log-generator

      - name: Set git user
        uses: fregante/setup-git-user@v2

      - name: Check for changes
        run: git status

      - name: Stage changed files
        run: git add .

      - name: Commit changed files
        run: "git commit -m 'Action: Update version in `Main.cs` and update `CHANGELOG.md`'"

      - name: Fetch from master
        run: git fetch origin master

      - name: Push code to master
        run: git push origin master

      - name: Build Executable
        run: dotnet build --configuration Release

      - name: Upload Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: release-windows
          path: bin/Release/net48/HKS-NoClip.dll
  
  upload:
    name: Create Release
    permissions:
      contents: write
    needs: [ windows-release-build ]
    runs-on: ubuntu-latest
    steps:
      - name: Download Build Artifacts
        uses: actions/download-artifact@v4

      - name: Create Release
        uses: ncipollo/release-action@v1
        with:
          artifacts: "release-windows/*.dll"
          token: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ needs.windows-release-build.outputs.new_tag }}
          name: Release ${{ needs.windows-release-build.outputs.new_tag }}
          body: ${{ needs.windows-release-build.outputs.changelog }}